language: android
android:
  components:
  - tools
  - tools
  - build-tools-26.0.0
  - android-25
  - extra-android-m2repository
jdk:
- oraclejdk8
after_success:
- build-scripts/deploy_snapshot.sh
env:
  global:
  - secure: Nk07J5Cg08KJ3Ry8tFF0ue1VO9itfMhw+r0Vp9q1IYpcP3SQ9e1lGLDYGDV51uCoQT/nrqJbw32uIqLm83luZG+c14e+CaPwtsvSGH1uyklu60uHmCeoO78FdHD/63wR+todM/AaD+ZW9vnPlhIMyw9NhbWa6/vVC/ecLdayDe+0lPPeVc+4hYnoQRFh+k+73v2RHyuzxTfEJE+qPoi/w7lvF35E3/OV18iZzBV36+zY//2tTlTR6hiyAeTbqYDn9fpndsLIghRetlp6DhQkRoMpiZUCAWb/ypmJLAjltWTyrags3BYz2aQSvmwwMpJE6jz/C6QtBSQ0gj4wXZh21siGzJBZYYEmo+24ZSg88/YNXLR2GkjYBK2YwjeJl8CWAc+aurO7MGhGc4tJFSmeKNOing0bI2RSRSibg6arKXgAzsL8uM8I/l9un9HbGPoBjj8xKL0+ww8a/ltYlkvA4R16jvc97sE2hD6hmy8hWi7DH189bQzzi5F+8jbhfEMygyJm7pJHIXYpZMFVZ2lXSBhhIIHIEOn+NXFnAAIvaHZ69WpIYAeMtFSAvq+CmyoOyB44i4QhqpoPUzIi9D/MK2hbKsxkI5BBrb/vS97zFAr25cAkOusGoAj51iiVPE2/kRD/TOVQcLxIpz9aovsOfA/T6zcyxy+iVjb8MJ68nvc=
  - secure: l+eItGP/pkeEg5a3Ag9KjlwV/qdJck+SeNOGuF1YNz8fmYK9SwItNQrnHSVXib6ccMo+OMXc/wPU5bYtGDIXwj9msGtU6o/P5U5ZwVQrDAPjbZIxTvvGqMFH4u/DJBAwoUeYsIwqtqYaY/2wgmBFpBypfFHQez3MKy2ZyUoPQqMRTmNJyD2IodC40QeyFPfP1/otoXXcBU5QNZevIIE5ICvEKvzDjxtbJEfkBHqIyuxLB0kG2ajoZXKN2N9EiHmjX8hEOhTxc8s7TcDELeVG5tlAkBOHUnt714N3cIh2vqS7JnQ61Eo2uJb7fMZeHiaHwVcDcAgXKZ5KlxccpOVryFDa1rciDMoeP2AXYxKe4yZz///MWeJb7gXgdsZRe+jUZNTl6u2MFzRZXNXO0ikc2vvx2B+PTeUpkzs3yiNAZb7P28N8ocjfYhHCmMELg/iFlg/whuGHUGsx2qUxY9IpOQXdfG4VJ+LxLAYSt4XspE+UGopFllEvryRy532zQ59gYBBitQglpOGNaXUUTt8uCvs+p27jrxxlRoh2yScS9nlGvhQgoXQqjQs8XQkX1iNosp/67jqhDn2b/mr5zFqWJFKI1WByYaGOwmx5GbVLhq4CWYDFueSyDT6uXctRgZuNomzIiIX/d0C+igD/s6tycamZshibqMtJ/etRi8NFsIY=
sudo: false
cache:
  directories:
  - $HOME/.gradle
